server:
  shutdown: graceful

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USER:root}
    password: ${DB_PWD:yhm75040611?}
    hikari:
      max-lifetime: 600000

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

  jackson:
    property-naming-strategy: SNAKE_CASE

  lifecycle:
    timeout-per-shutdown-phase: 20s

jwt:
  secret-key: ${JWT_SECRET_KEY:souso}
  access-exp: ${JWT_ACCESS_EXP:2592000000} # 30일
  refresh-exp: ${JWT_REFRESH_EXP:2592000000} # 30일

coolsms:
  key: ${COOLSMS_API_KEY}
  secret: ${COOLSMS_SECRET_KEY}
  phone-number: ${COOLSMS_PHONE_NUMBER}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET:meet}
      endpoint: ${S3_ENDPOINT:https://kr.object.ncloudstorage.com}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

springdoc:
  swagger-ui:
    path: /api-test  # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.
    groups-order: DESC # path, query, body, response 순으로 출력
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능
  paths-to-match:
    - /v1/** # swagger-ui에 표시할 api의 엔드포인트 패턴
