spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd'T'HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

  jwt:
    header: Authorization
    secret-key: ${JWT_SECRET_KEY}
    access-exp: 2592000000   # 30일
    refresh-exp: 2592000000   # 30일
    prefix: Bearer

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        endpoint: ${AWS_S3_ENDPOINT}
        bucket: ${AWS_S3_BUCKET}

springdoc:
  swagger-ui:
    path: /api-test
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match:
    - /v1/**
